apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: custom-gitclone-repo
spec:
  url: https://github.com/your-org/your-repo
  pipelineRunSpec:
    pipelineRef:
      name: simple-pipeline
    params:
      - name: repo-url
        value: https://github.com/your-org/your-repo
      - name: branch
        value: main
    workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: shared-workspace-pvc
