apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: custom-gitclone-repo
spec:
  url: https://github.com/sudhishmk/rhpamexample.git
  pipelineRunSpec:
    pipelineRef:
      name: simple-pipeline
    params:
      - name: repo-url
        value: https://github.com/sudhishmk/rhpamexample.git
      - name: branch
        value: master
    workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: shared-workspace-pvc
